---
deployment:
  tasks:
    - export DEPLOYPATH=/home/dxadlyne/public_html/
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R scripts $DEPLOYPATH
    - /bin/cp -R styles $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp singleModel.html $DEPLOYPATH
